### ISSUE TITLE
RCTViewManager   RCTView 

### ISSUE THREAD

**Issue by zhangrundong** [alinz/react-native-webview-bridge#224] opened 2017-04-13 06:42 UTC
![image](https://cloud.githubusercontent.com/assets/16918482/24993107/7074c874-2057-11e7-9b59-1fec7f256c0e.png)

**Comment by swaroopa94** [comment] 2017-04-21 09:05
Same issue please anyone help

**Comment by arjshiv** [comment] 2017-04-23 02:49
Same issue here, too

**Comment by arjshiv** [comment] 2017-04-23 02:56
But works when pulling from `master` - so possibly related to https://github.com/alinz/react-native-webview-bridge/pull/217 ?

**Comment by vsrboth** [comment] 2017-04-25 09:34
The issue is still here. I am using 

RN: 0.42.0
react-native-webview-bridge: 0.33.0

Can anyone help out?
Thank you so much.

**Comment by kingfun2015** [comment] 2017-04-26 09:16
the same issue.
with using 
"react-native": "0.40.0",
"react-native-webview-bridge": "^0.33.0"

**Comment by kingfun2015** [comment] 2017-04-26 09:53
You can see here to solve this issue.
[https://github.com/alinz/react-native-webview-bridge/issues/219](url)

**Comment by kingfun2015** [comment] 2017-04-26 10:02
If your react-native version more than 0.40,please to change the header file like this 
#import "RCTWebViewBridge.h"

#import <UIKit/UIKit.h>

#import <React/RCTAutoInsetsProtocol.h>
#import <React/RCTConvert.h>
#import <React/RCTEventDispatcher.h>
#import <React/RCTLog.h>
#import <React/RCTUtils.h>
#import <React/RCTView.h>
#import <React/UIView+React.h>
#import <objc/runtime.h>

**Comment by iOSHw** [comment] 2017-05-09 11:38
Nobody can give a correct answer?

**Comment by Philipwzj** [comment] 2017-06-02 19:48
Same problem

**Comment by rogerluo410** [comment] 2017-06-09 08:58
The functionality has already added into RN core module. 

So, the author maybe doesn't maintain the repo anymore...    

Look at: https://github.com/alinz/react-native-webview-bridge/issues/206

**Comment by eric-muyser-hs** [comment] 2017-07-04 21:25
@kingfun2015 That doesn't work. I suspect it's building RCTView etc. into the library and conflicting. Should be dynamically linked? That's a project setting right?

**Comment by eric-muyser-hs** [comment] 2017-07-04 22:07
I have a fix, will post diff later. Basically just move the .h includes from the .m into the .h and change to `<>` not `""`

**Comment by ericmuyser** [comment] 2017-07-05 18:52
Fix is in PR #230 if anybody needs it

**Closed** 2017-07-25 12:33 UTC
