### ISSUE TITLE
Error when being used inside a Navigator 

### ISSUE THREAD

**Issue by jjshammas** [alinz/react-native-webview-bridge#27] opened 2015-10-12 02:27 UTC
When the bridge is used inside of a navigator scene, and the scene is unmounted, I get this error:

<img width="487" alt="screen shot 2015-10-11 at 10 26 11 pm" src="https://cloud.githubusercontent.com/assets/2018797/10420686/3d66e4fe-7067-11e5-98c3-5889f7ebc36d.png">

Any ideas on a fix?

**Comment by Prometheuser** [comment] 2015-10-12 07:34
same situation...

**Comment by carbonphyber** [comment] 2015-10-13 20:17
Duplicate of [ Crashes app while navigating webView pages from one to other #22 ](https://github.com/alinz/react-native-webview-bridge/issues/22).

**Comment by CorpusCallosum** [comment] 2015-11-09 15:41
+1

**Comment by gs-akhan** [comment] 2015-11-12 08:05
Does this fail ? When you use this inside <NavigatorIOS> or some link navigation inside webview ?
Thanks

**Comment by CorpusCallosum** [comment] 2015-11-23 16:26
Hi I was able to circumvent the error by wrapping the cleanup call back in a try-catch. I created a fork here: https://github.com/CorpusCallosum/react-native-webview-bridge

You can install it via NPM by adding this line in your package.json dependencies:
"react-native-webview-bridge": "https://github.com/CorpusCallosum/react-native-webview-bridge/tarball/master"

**Comment by alinz** [comment] 2015-12-09 18:44
@jjshammas the new version will fix this issue since. Please reopen this issue if you have the same error.

**Closed by alinz** 2015-12-09 18:44 UTC

**Comment by CorpusCallosum** [comment] 2015-12-09 20:28
Hi @alinz thanks for your fix. I just tried to upgrade the packages, but now when I run my xcode project, I get the following error:
```
clang: error: no such file or directory: '/Users/jkalish/Documents/Work/IBM Studio/TA15/ta15-native-app/node_modules/react-native-webview-bridge/WebViewBridge/RCTWebViewManager+WebViewManager.m'
clang: error: no input files
 ```

Looks like it's trying to reference the original class paths, that have changed. How can I fix this?

**Comment by alinz** [comment] 2015-12-09 21:09
@CorpusCallosum couple of things:
1: what version of react are you using? the latest version of WebViewBridge needs to be run with React-native 0.16 and above. I have a plan to make 0.15 and 0.14 but I only support 0.16.
2: Make sure you remove `react-native-webview-bridge` folder from your `node_modules`. remove `.a` files from `Target` section and remove `projxcode` from `Library` then follow the instruction.

**Comment by CorpusCallosum** [comment] 2015-12-09 21:42
@alinz Thanks for the quick reply. As it turns out I still had the original version of the library class files in my xcode project Libraries folder. I had to remove these and add the new project file, and now it builds.
