### ISSUE TITLE
Sending a string that has a single quote in it breaks sendToBridge

### ISSUE THREAD

**Issue by dozoisch** [alinz/react-native-webview-bridge#80] opened 2016-04-09 19:26 UTC
I managed to repro this with a very small string.

If you do 

```js
// ...
onLoad() {
  var e = "12'3"; // Notice the single quote;
  this.refs.webview.sendToBridge(e);
}
```

I get an from my webview error saying:  `{"error":"SyntaxError: Unexpected EOF"}`

I tried with a few other strings/objects (and stringifying them) with single quotes and it always error.

There is probably an inlining somewhere of the message string that is not escaped. I'm trying to find the exact cause.

on iOS, using version: 0.20.3

**Comment by overminder** [comment] 2016-04-14 06:19
Seems to be caused by [this](https://github.com/alinz/react-native-webview-bridge/blob/f116c8d/ios/RCTWebViewBridge.m#L96).

Need to find a way to properly convert a NSString into an escaped JS string literal.

**Comment by paolocaminiti** [comment] 2016-09-21 12:01
This worked for me:

ios:CTWebViewBridge.m:97
```objectivec
- (void)sendToBridge:(NSString *)message
{
  //we are warpping the send message in a function to make sure that if
  //WebView is not injected, we don't crash the app.
  NSString *format = NSStringMultiline(
    (function(){
      if (WebViewBridge && WebViewBridge.__push__) {
        WebViewBridge.__push__('%@');
      }
    }());
  );
  // escape all double escapes to make the survive as literal '\' by the time the get to js
  message = [message stringByReplacingOccurrencesOfString:@"\\\\" withString:@"\\\\\\\\"];
  // unescaped the just escaped new lines, note: this disallow passing a litteral '\n' around
  message = [message stringByReplacingOccurrencesOfString:@"\\\\\\\\n" withString:@"\\\\n"];
  // escape nested double quotes which come already escaped
  message = [message stringByReplacingOccurrencesOfString:@"\\\"" withString:@"\\\\\""];
  // escape single quotes to allow the format to be valid js
  message = [message stringByReplacingOccurrencesOfString:@"'" withString:@"\\'"];
  NSString *command = [NSString stringWithFormat: format, message];
  [_webView stringByEvaluatingJavaScriptFromString:command];
}
```
android:WebViewBridgeManager.java:64
```java
private void sendToBridge(WebView root, String message) {
    message = message.replaceAll("\\\\", "\\\\\\\\").replaceAll("'", "\\\\'");
    String script = "WebViewBridge.onMessage('" + message + "');";
    root.evaluateJavascript(script, null);
}
```

Note that in the ios version you lose the possibility to pass a litteral escaped '\n' around, as double escaped '\n' will always end up in single escaped '\n'.

I tried with no luck to have the ios version work via regexps, something like /\\\\(?![ntr])/g would work in js to escape all but break control characters, but gave me weired results so I gave up and do the multiple string replacement.

Also note that I only tested java from kitakat 4.4, I see this repo has introuced message passing using javascript:URL navigation for older versions, and I suppose that would break as well unless further escaping is applied.

Hope this can help, but I suppose it's too much of a hack to propose a pull request.

**Comment by alinz** [comment] 2016-10-04 16:56
@dozoisch I took a different approach which let me sends any type of data back and forth, and as you guest, base64. By using base64 technically we can send even binary data, not tested yet, but theoretically should work. We, @hmedney and I are refining the API and soon a new version of webview bridge will be released. but in a meantime you can checkout the v2 branch and take a look at the code.

For now I'm going to close this ticket. Please feel free to continue the discussion.

**Closed by alinz** 2016-10-04 16:56 UTC
