### ISSUE TITLE
NSUnknownKeyException

### ISSUE THREAD

**Issue by dvine-multimedia** [alinz/react-native-webview-bridge#29] opened 2015-10-17 00:33 UTC
I get this error just by instantiating the WebViewBridge. The full error is:

2015-10-16 20:24:11.076 iphoneDEV[84420:4635019] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSUnknownKeyException> [<RCTWebView 0x7fd3ec0e4750> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _eventDispatcher.

After digging around a bit I don't think that WebKit has actually anything to do with it. But I have no idea where this could come from.

I'm using react-native 0.13.0-rc

**Comment by gre** [comment] 2015-10-20 11:34
same issue

**Comment by carbonphyber** [comment] 2015-10-21 00:00
same issue.
I got it after updating my `react-native` from `0.10.0` to `0.12.0` and node from `0.x.y` to `4.2.1`.

**Comment by carbonphyber** [comment] 2015-10-21 19:59
Just confirmed this exists in `react-native-webview-bridge` (new react-native app with no other components/dependencies) running on `node 4.2.1`.

    "react-native": "^0.12.0",
    "react-native-webview-bridge": "^0.3.6"

**Comment by carbonphyber** [comment] 2015-10-21 21:47
I was able to reproduce this issue after I converted the `WebViewBridge` component to a `WebView` component. It might be the underlying react native component or possibly something the two components have in common.

**Comment by NoelBaron** [comment] 2015-10-26 19:44
I experienced this issue after switching from `WebView` to `WebViewBridge`.

**Comment by NoelBaron** [comment] 2015-10-26 20:06
Reverted from ```react-native 0.13.1``` to ```react-native 0.11.4```.  
Issue resolved.

**Comment by rick-li** [comment] 2015-11-04 21:32
Looks like webViewBridge uses private _eventDispatcher from RCTWebView, however that variable has been removed in latest release. see https://github.com/facebook/react-native/commit/848839858b4f4e03b83e625304af21aa8dd8ff05

**Comment by alinz** [comment] 2015-11-05 05:00
I have merge the the PR from @rick-li, it should be fixed now.

**Closed by alinz** 2015-11-05 05:00 UTC

**Comment by dvine-multimedia** [comment] 2015-11-05 16:12
Great, thanks a lot @alinz and @rick-li !!
